import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ListPlanets } from 'features';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>List Of Planets</title>
        <meta name="description" content="Generated by Muhammad Rayandika" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ListPlanets />
    </div>
  );
};

export default Home;
